# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20b1eee4aed54eab27c5c27214553c2aa70c29d242e8b00dda40fe13d63a2628bb53577d0746d96706c89a1f2b3cd0335afb871bf65292daf9fe34ff50c80edf

test:
  secret_key_base: 5a70948dcc21275435e472112947f282a97feedf324f4cbef7b6df9667d5c77c6f6333cae6000397c28607c76d82e1ce4974dd2f1ea6ac5beb98709c76309fa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
